version: "3.7"
services:
  traefik:
    image: traefik:chevrotin
    container_name: traefik
    networks:
      - outside
    command:
      # docker backend
      - "--providers.docker=true"
      # services are not exposed by default
      - "--providers.docker.exposedbydefault=false"
      # dynamic configuration folder
      - "--providers.file.directory=/dc"
      # enable dashboard
      - "--api"
      # enable HTTP entrypoint and redirect to HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # enable HTTPS entrypoint
      - "--entrypoints.websecure.address=:443"
      # enable TLS
      - "--entrypoints.websecure.http.tls=true"
      # Let's encrypt SSL certificate
      - "--entrypoints.websecure.http.tls.certresolver=le"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=name@domain.localhost"
      - "--certificatesresolvers.le.acme.storage=/le/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dc:/dc"
      - "./le:/le"
    labels:
      - "traefik.enable=true"
      # configure the access to the dashboard
      - "traefik.http.routers.traefik.rule=Host(`api.domain.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      # authentication user/hashed-password for dashboard
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=user:hashed-password"

# create a network to the outside for traefik
networks:
  outside:
    name: traefik-outside-net
