# set HSTS headers in middleware
# follow recommendations from https://infosec.mozilla.org/guidelines/web_security
[http]
  [http.middlewares]
    [http.middlewares.hsts-headers]
      [http.middlewares.hsts-headers.headers]
        stsSeconds = 63072000
        stsIncludeSubdomains = true
        # stsPreload = true # only if site is on the HSTS preload list
        frameDeny = true
        customFrameOptionsValue = "DENY"
        contentTypeNosniff = true
        browserXssFilter = true
        contentSecurityPolicy = "default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'" # do not load any resources and disable framing
        referrerPolicy = "same-origin"
        featurePolicy = "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none'; vibrate 'none'"
        [http.middlewares.hsts-headers.headers.customResponseHeaders]
          X-Powered-By = ""
          X-Robots-Tag = "noindex, noarchive, nosnippet"

# set TLS options according to Mozilla SSL config
# using intermediate settings as default
[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      sniStrict = true
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      ]
    [tls.options.modern]
      minVersion = "VersionTLS13"
      sniStrict = true
