# set security headers in middleware
[http]
  [http.middlewares]
    [http.middlewares.security-headers]
      [http.middlewares.security-headers.headers]
        stsSeconds = 31536000
        stsIncludeSubdomains = true
        frameDeny = true
        customFrameOptionsValue = "SAMEORIGIN"
        contentTypeNosniff = true
        browserXssFilter = true
        contentSecurityPolicy = "default-src 'self'"
        referrerPolicy = "same-origin"
        featurePolicy = "vibrate 'none';"

# set TLS options according to Mozilla SSL config
[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      sniStrict = true
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      ]
    [tls.options.modern]
      minVersion = "VersionTLS13"
      sniStrict = true